#!/usr/bin/env bash

set -x 

cd "$HOME" || exit

# check for git installation
if ! [ -x "$(command -v git)" ]; then
  echo 'git is not installed' >&2
  exit 1
fi

# check for existing config repo
if ! test -d "$HOME/.cfg" ; then
  echo Cloning dotfiles
  git clone https://github.com/ecshreve/figgy.git "$HOME/.cfg"

  # git clone --bare https://github.com/ecshreve/figgy.git "$HOME/.cfg"
  # git --git-dir="$HOME/.cfg/" --work-tree="$HOME" checkout
  # git --git-dir="$HOME/.cfg/" --work-tree="$HOME" pull --force
fi

if ! which python3 1>/dev/null 2>&1 ; then
  echo Installing python3
  sudo apt-get update -y
  sudo apt-get install -y python3
fi

if ! which pip 1>/dev/null 2>&1 ; then
  echo Installing pip
  sudo apt-get update -y
  sudo apt-get install -y python3-pip
fi

if ! which ansible 1>/dev/null 2>&1 ; then
  echo Installing ansible
  python3 -m pip install --user ansible
  python3 -m pip install --user ansible-lint
fi

echo "Moving config files"
mkdir -p $HOME/.config/fish
cp -r $HOME/.cfg/.config/fish $HOME/.config/fish

echo "Running ansible playbook"
ansible-playbook $HOME/.cfg/ansible/playbook.yml -vvv

fish -c 'setup'

exit 0
